spring.application.name=backend

# Ativa o perfil de produção
spring.profiles.active=prod

# JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update