spring.application.name=backend

# Ativa o perfil de produção
spring.profiles.active=dev

# JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#OpenAI
openai.api.key=OPEN_AI_KEY
openai.api.url=https://api.openai.com/v1/chat/completions

# Gemini API GRATUITA
gemini.api.key=AIzaSyDA_TSprpFfURixZwoUC2zOuaWZTeEZp9g
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions


#smtp gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=physiotrack10@gmail.com
spring.mail.password=ehww mpnr ispc ysct
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

