# Configurações do PostgreSQL (Heroku define via DATABASE_URL)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações do Flyway
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migrations
