CREATE TABLE dummy (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(10) NULL,
                         status boolean NOT NULL DEFAULT true,
                         CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE estado (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        sigla VARCHAR(2) NOT NULL
);

CREATE TABLE cidade (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        estado_id BIGINT NOT NULL,
                        CONSTRAINT fk_estado FOREIGN KEY (estado_id) REFERENCES estado (id)
);

CREATE TABLE endereco (
                          id BIGSERIAL PRIMARY KEY,
                          rua VARCHAR(255) NOT NULL,
                          estado VARCHAR(100) NOT NULL,
                          cep VARCHAR(20) NOT NULL,
                          cidade_id BIGINT NOT NULL,
                          CONSTRAINT fk_cidade FOREIGN KEY (cidade_id) REFERENCES cidade (id)
);

CREATE TABLE pessoa (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        cpf VARCHAR(14) NOT NULL UNIQUE,
                        telefone VARCHAR(20),
                        endereco_id BIGINT,
                        ativo BOOLEAN NOT NULL DEFAULT true,
                        CONSTRAINT fk_endereco_pessoa FOREIGN KEY (endereco_id) REFERENCES endereco (id)
);


CREATE TABLE usuario (
                         id BIGSERIAL PRIMARY KEY,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         senha VARCHAR(255) NOT NULL,
                         role VARCHAR(50) NOT NULL,
                         tipo_usuario VARCHAR(50) NOT NULL,
                         pessoa_id BIGINT UNIQUE,
                         CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id)
);


CREATE TABLE atendimento (
                             id BIGSERIAL PRIMARY KEY,
                             usuario_id BIGINT NOT NULL,
                             paciente_id BIGINT NOT NULL,
                             tipo_atendimento VARCHAR(100) NOT NULL,
                             data_atendimento TIMESTAMP NOT NULL,
                             descricao TEXT,
                             CONSTRAINT fk_usuario_atendimento FOREIGN KEY (usuario_id) REFERENCES usuario (id),
                             CONSTRAINT fk_paciente_atendimento FOREIGN KEY (paciente_id) REFERENCES pessoa (id)
);

CREATE TABLE imagem (
                        id BIGSERIAL PRIMARY KEY,
                        url VARCHAR(255) NOT NULL,
                        descricao TEXT,
                        tipo_imagem VARCHAR(100),
                        atendimento_id BIGINT NOT NULL,
                        CONSTRAINT fk_atendimento_imagem FOREIGN KEY (atendimento_id) REFERENCES atendimento (id)
);

CREATE TABLE avaliacao (
                           id BIGSERIAL PRIMARY KEY,
                           atendimento_id BIGINT NOT NULL,
                           data DATE,
                           altura DOUBLE PRECISION,
                           peso DOUBLE PRECISION,
                           imc DOUBLE PRECISION,
                           esporte TEXT,
                           queixas TEXT,
                           historico_saude TEXT,
                           medicamentos TEXT,
                           cirurgia TEXT,
                           tratamento_anterior TEXT,
                           exame_imagem TEXT,
                           diagnostico_medico TEXT,
                           obj_tratamento TEXT,
                           obs_gerais TEXT,

                           perimetria_medida1d DOUBLE PRECISION,
                           perimetria_medida2d DOUBLE PRECISION,
                           perimetria_medida3d DOUBLE PRECISION,
                           perimetria_panturrilhad DOUBLE PRECISION,

                           perimetria_assimetria_medida1e DOUBLE PRECISION,
                           perimetria_assimetria_medida2e DOUBLE PRECISION,
                           perimetria_assimetria_medida3e DOUBLE PRECISION,
                           perimetria_panturrilhae DOUBLE PRECISION,

                           perimetria_medida_ass1 DOUBLE PRECISION,
                           perimetria_medida_ass2 DOUBLE PRECISION,
                           perimetria_medida_ass3 DOUBLE PRECISION,
                           perimetria_panturrilha_ass DOUBLE PRECISION,

                           lunged DOUBLE PRECISION,
                           lungee DOUBLE PRECISION,
                           lunge_ass DOUBLE PRECISION,

                           rot_quad_interd DOUBLE PRECISION,
                           rot_quad_intere DOUBLE PRECISION,
                           rot_quad_inter_ass DOUBLE PRECISION,

                           rot_quad_exterd DOUBLE PRECISION,
                           rot_quad_extere DOUBLE PRECISION,
                           rot_quad_exter_ass DOUBLE PRECISION,

                           ext_joelhod DOUBLE PRECISION,
                           ext_joelhoe DOUBLE PRECISION,
                           ext_joelho_ass DOUBLE PRECISION,

                           flex_joelhod DOUBLE PRECISION,
                           flex_joelhoe DOUBLE PRECISION,
                           flex_joelho_ass DOUBLE PRECISION,

                           sh_test1d DOUBLE PRECISION,
                           sh_test2d DOUBLE PRECISION,
                           sh_test3d DOUBLE PRECISION,
                           sh_test_mediad DOUBLE PRECISION,

                           sh_test1e DOUBLE PRECISION,
                           sh_test2e DOUBLE PRECISION,
                           sh_test3e DOUBLE PRECISION,
                           sh_test_mediae DOUBLE PRECISION,

                           sh_test_score DOUBLE PRECISION,
                           slb_testd DOUBLE PRECISION,
                           slb_teste DOUBLE PRECISION,

                           CONSTRAINT fk_atendimento_avaliacao FOREIGN KEY (atendimento_id) REFERENCES atendimento (id)
);

