CREATE TABLE dummy (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(10) NULL,
                         status boolean NOT NULL DEFAULT true,
                         CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE pessoa (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        cpf VARCHAR(14) NOT NULL UNIQUE,
                        telefone VARCHAR(20)
);

CREATE TABLE usuario (
                         id BIGSERIAL PRIMARY KEY,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         senha VARCHAR(255) NOT NULL,
                         role VARCHAR(50) NOT NULL,
                         tipo_usuario VARCHAR(50) NOT NULL,
                         pessoa_id BIGINT UNIQUE,
                         CONSTRAINT fk_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id)
);

CREATE TABLE estado (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        sigla VARCHAR(2) NOT NULL
);

CREATE TABLE cidade (
                        id BIGSERIAL PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        estado_id BIGINT NOT NULL,
                        CONSTRAINT fk_estado FOREIGN KEY (estado_id) REFERENCES estado (id)
);

CREATE TABLE endereco (
                          id BIGSERIAL PRIMARY KEY,
                          rua VARCHAR(255) NOT NULL,
                          estado VARCHAR(100) NOT NULL,
                          cep VARCHAR(20) NOT NULL,
                          pessoa_id BIGINT NOT NULL,
                          cidade_id BIGINT NOT NULL,
                          CONSTRAINT fk_pessoa_endereco FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
                          CONSTRAINT fk_cidade FOREIGN KEY (cidade_id) REFERENCES cidade (id)
);

CREATE TABLE atendimento (
                             id BIGSERIAL PRIMARY KEY,
                             usuario_id BIGINT NOT NULL,
                             paciente_id BIGINT NOT NULL,
                             tipo_atendimento VARCHAR(100) NOT NULL,
                             data TIMESTAMP NOT NULL,
                             descricao TEXT,
                             CONSTRAINT fk_usuario_atendimento FOREIGN KEY (usuario_id) REFERENCES usuario (id),
                             CONSTRAINT fk_paciente_atendimento FOREIGN KEY (paciente_id) REFERENCES pessoa (id)
);

CREATE TABLE imagem (
                        id BIGSERIAL PRIMARY KEY,
                        url VARCHAR(255) NOT NULL,
                        descricao TEXT,
                        tipo_imagem VARCHAR(100),
                        atendimento_id BIGINT NOT NULL,
                        CONSTRAINT fk_atendimento_imagem FOREIGN KEY (atendimento_id) REFERENCES atendimento (id)
);

CREATE TABLE avaliacao (
                           id BIGSERIAL PRIMARY KEY,
                           atendimento_id BIGINT NOT NULL,
                           CONSTRAINT fk_atendimento_avaliacao FOREIGN KEY (atendimento_id) REFERENCES atendimento (id)
);